title: "CO2RR Guide: A Beginner's Guide to CO2 Reduction"
description: "The ultimate beginner's guide to Electrochemical CO2 Reduction (CO2RR). Explore interactive tutorials on CO2RR theory, H-cell experimental setup, data analysis, and troubleshooting."
url: "https://Wit-K.github.io"
baseurl: "/Guide-to-CO2-Reduction" 
theme: jekyll-theme-cayman
markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
google_site_verification: ah28mJspExOlFQ4EJ7a6s3A4GzVnMpcdmzomSRGbgp8
